### ISSUE TITLE
AttributeError with 'v2' branch

### ISSUE THREAD

**Issue by sdegrande** [TkTech/notifico#205]
Hello.

In order to try to find a fix for Giteas webhook, I tried to install notifico on my Fedora 36.
I created a python2.7 virtualenv, but one the dependencies does not build.
So I checkout the v2 branch (which seems to be your active dev branch...), in a py3.10 venv.
"Poetry install" did its job with no errors.
I created the local_config.py, ran "notifico db upgrade" and "notifico run".

I was able to register on the website, create a project, and then I tried to create a new hook and got the following error.

I guess that the 'v2' branch is not yet stable, but I would really like to help fixing the Giteas hook issue...

```
127.0.0.1 - - [10/Jul/2022 18:44:10] "GET /fluzz/FreedroidRPG/hook/new HTTP/1.1" 500 -
[2022-07-10 18:54:01,818] ERROR in app: Exception on /fluzz/FreedroidRPG/hook/new/20 [GET]
Traceback (most recent call last):
  File "/home/degrande/notifico-env/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/degrande/notifico-env/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/degrande/notifico-env/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/degrande/notifico-env/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/degrande/notifico-env/lib/python3.10/site-packages/notifico/__init__.py", line 36, in _wrapped
    return f(*args, **kwargs)
  File "/home/degrande/notifico-env/lib/python3.10/site-packages/notifico/views/projects/__init__.py", line 95, in _wrapped
    return f(*args, **kwargs)
  File "/home/degrande/notifico-env/lib/python3.10/site-packages/notifico/views/projects/__init__.py", line 266, in new_hook
    hook = HookService.services.get(sid)
AttributeError: type object 'HookService' has no attribute 'services'
```

**Comment by sdegrande** [comment]
Lot of them actually...

I instead installed a CentOS7 VM, with python 2.7, in order to run the master's version. So I can now try to track the issue with giteas.

**Comment by sdegrande** [comment]
I finally have a working gitea + notifico setup.
Given that I work on the 'master' branch, I'll now switch to issue #178
